dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - yarn
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs

script: vendor/bin/phpunit tests --whitelist src --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
